import { CircleAlert } from 'lucide-react'

import { useSlate } from '@/app/slate-context'
import { Select } from '@/components/ui/Select'
import { Tooltip } from '@/components/ui/Tooltip'
import { formatScoringProfile } from '@/utils/format'
import { cn } from '@/utils/cn'

/**
 * Season, week and scoring format — the selection every view reads.
 *
 * Both lists are built from `/seasons`, which reports only what has a
 * *published* board. Offering week 4 when nothing is published for it — or
 * 2003, which the warehouse has games for and no projection run has ever
 * covered — produces an empty screen the user cannot explain. So neither is
 * offered, and a season with no published run at all says so instead of
 * presenting an empty dropdown.
 */
export function SlateControls({ className, compact = false }: { className?: string; compact?: boolean }) {
  const slate = useSlate()
  const size = compact ? 'md' : 'sm'

  const seasonOptions = slate.availableSeasons.map((season) => ({
    value: String(season),
    label: String(season),
  }))

  // A `?season=` naming something unpublished is honoured rather than
  // overridden — it is an explicit request, and the week control beside this one
  // explains what is missing. But it has to appear in its own selector, or the
  // control renders blank and the app looks broken at exactly the moment it is
  // trying to explain itself.
  if (slate.season !== null && !slate.availableSeasons.includes(slate.season)) {
    seasonOptions.unshift({ value: String(slate.season), label: `${slate.season}` })
  }

  const weekOptions = slate.availableWeeks.map((week) => ({
    value: String(week),
    label: `Week ${week}`,
  }))

  const profileOptions = slate.availableProfiles.map((profile) => ({
    value: profile,
    label: formatScoringProfile(profile),
  }))

  const noPublishedWeeks = slate.availableWeeks.length === 0
  // A selector with nothing in it is either still loading or broken, and those
  // need different words. Saying "Loading…" forever is the worse of the two.
  const placeholder = slate.catalogFailed ? 'Unavailable' : 'Loading…'

  return (
    <div className={cn('flex flex-wrap items-end gap-2', className)}>
      <Select
        label="Season"
        hideLabel={!compact}
        size={size}
        value={slate.season === null ? '' : String(slate.season)}
        options={seasonOptions.length > 0 ? seasonOptions : [{ value: '', label: placeholder }]}
        disabled={seasonOptions.length === 0}
        onChange={(event) => slate.setSeason(Number(event.target.value))}
        className={compact ? 'flex-1' : 'w-24'}
      />

      {/*
        "No published weeks" is a statement about the data, so it must not be
        shown when the real problem is that we could not reach the API at all.
      */}
      {noPublishedWeeks && !slate.catalogFailed ? (
        <Tooltip content="No projection run has been published for this season yet. The board is generated by the weekly job.">
          <span className="border-line bg-surface-sunken text-ink-muted inline-flex h-8 items-center gap-1.5 rounded-[var(--radius-control)] border px-2.5 text-xs">
            <CircleAlert aria-hidden className="size-3.5" />
            No published weeks
          </span>
        </Tooltip>
      ) : (
        <Select
          label="Week"
          hideLabel={!compact}
          size={size}
          value={slate.week === null ? '' : String(slate.week)}
          options={weekOptions.length > 0 ? weekOptions : [{ value: '', label: placeholder }]}
          disabled={weekOptions.length === 0}
          onChange={(event) => slate.setWeek(Number(event.target.value))}
          className={compact ? 'flex-1' : 'w-28'}
        />
      )}

      <Select
        label="Scoring"
        hideLabel={!compact}
        size={size}
        value={slate.scoringProfile ?? ''}
        options={profileOptions.length > 0 ? profileOptions : [{ value: '', label: placeholder }]}
        disabled={profileOptions.length === 0}
        onChange={(event) => slate.setScoringProfile(event.target.value)}
        className={compact ? 'flex-1' : 'w-32'}
      />
    </div>
  )
}
