"""Track record: every stored projection, graded against what happened.

The frozen foundation (:mod:`nflfp.predict.foundation`) records what the model
measured on a walk-forward backtest when it was validated. This module answers a
different question about a different set of numbers: of the projections this
deployment actually *stored* — the published run for every week — how often did
the outcome land inside the stated range, and how far off was the centre?

Both are honest and they must not be confused. The validation record is a
fixed measurement that promoted the model; the track record is a live
aggregate that grows every week a game completes. The response carries the
validation figures beside the live ones so a reader can compare them, and never
substitutes one for the other.

What is graded, and what is not
-------------------------------
A player-week is graded when a published run stored a projection for it *and*
the warehouse holds a stat line for it. A projected player with no stat line did
not play; there is no outcome to grade, and counting it as zero points would
grade the injury report rather than the model. That exclusion is stated in the
response, not left for a reader to discover.

How the stored runs were produced matters to what this record means. The
historical runs were generated by ``backfill_projections``, which walks the same
``generate_week`` the weekly job calls, each week fitted only on games before it.
They are out-of-sample in exactly the walk-forward sense the validation used —
but they were produced after the fact, not published live on each Tuesday, and
the response says so.

Provenance: every figure here is ``derived`` — computed from ``model`` outputs
and ``actual`` outcomes, and consumed by nothing upstream.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from sqlalchemy.ext.asyncio import AsyncSession

from . import repository
from .catalog import resolve_scoring_profile

logger = logging.getLogger(__name__)

#: Beats and misses shown for one week. Enough to see a pattern, few enough to
#: read — and the full week is one filter away on the board.
SCORECARD_SIZE = 8

#: A player-week enters the scorecard only when it was projected at least this
#: high. Below it the "biggest miss" list fills with backups who scored a
#: garbage-time touchdown — true, and useless to a manager, who never started
#: them. Stated in the response so the filter is not invisible.
SCORECARD_MIN_PROJECTION = 8.0

#: Fewer graded player-weeks than this and a group's figures are reported with
#: a thin-sample flag rather than presented as a rate.
THIN_SAMPLE = 100

NOTICE_BACKFILL = (
    "Historical runs were generated by backfilling the frozen model week by week, "
    "each week fitted only on games played before it — out-of-sample in the same "
    "walk-forward sense as the validation, but produced after the fact rather than "
    "published live at the time."
)
NOTICE_DID_NOT_PLAY = (
    "Only player-weeks with a recorded stat line are graded. A projected player who "
    "did not play is excluded, not counted as zero points."
)


@dataclass(frozen=True)
class Accuracy:
    """How a group of stored projections fared.

    ``coverage_80`` is the share of outcomes inside the published P10-P90
    range, whose nominal rate is 0.80; ``coverage_50`` the same for P25-P75
    against 0.50. ``bias`` is projected minus actual, so a positive bias means
    the projections ran high.
    """

    graded: int
    mean_absolute_error: float | None
    bias: float | None
    interval_graded: int
    coverage_80: float | None
    coverage_50: float | None
    boom_predicted: float | None
    boom_observed: float | None
    bust_predicted: float | None
    bust_observed: float | None
    season: int | None = None
    week: int | None = None
    position: str | None = None
    band_low: float | None = None
    band_high: float | None = None

    @property
    def thin(self) -> bool:
        return self.graded < THIN_SAMPLE


@dataclass(frozen=True)
class Outcome:
    """One player-week, as stored and as played."""

    player_id: str
    name: str
    headshot_url: str | None
    position: str | None
    team: str | None
    opponent: str | None
    is_home: bool | None
    projected: float
    floor: float | None
    ceiling: float | None
    actual: float

    @property
    def difference(self) -> float:
        """Actual minus projected: positive is a beat."""
        return self.actual - self.projected

    @property
    def inside_range(self) -> bool | None:
        if self.floor is None or self.ceiling is None:
            return None
        return self.floor <= self.actual <= self.ceiling


@dataclass(frozen=True)
class Scorecard:
    season: int
    week: int
    summary: Accuracy | None
    beats: tuple[Outcome, ...]
    misses: tuple[Outcome, ...]
    min_projection: float


@dataclass(frozen=True)
class TrackRecord:
    scoring_profile: str
    season: int | None
    seasons: tuple[int, ...]
    overall: Accuracy | None
    by_position: tuple[Accuracy, ...]
    by_season: tuple[Accuracy, ...]
    by_season_position: tuple[Accuracy, ...]
    by_band: tuple[Accuracy, ...]
    weekly: tuple[Accuracy, ...]
    scorecard: Scorecard | None
    notices: tuple[str, ...]


def _float(row: Mapping[str, object], key: str) -> float | None:
    value = row.get(key)
    return None if value is None else float(value)  # type: ignore[arg-type]


def _int(row: Mapping[str, object], key: str) -> int | None:
    value = row.get(key)
    return None if value is None else int(value)  # type: ignore[call-overload]


def accuracy_from_row(row: Mapping[str, object]) -> Accuracy:
    """One aggregate row into an :class:`Accuracy`, keeping only its own keys."""
    band = _float(row, "band")
    rolled = lambda key: bool(row.get(f"g_{key}"))  # noqa: E731
    return Accuracy(
        graded=int(row.get("graded") or 0),  # type: ignore[call-overload]
        mean_absolute_error=_float(row, "mean_absolute_error"),
        bias=_float(row, "bias"),
        interval_graded=int(row.get("interval_graded") or 0),  # type: ignore[call-overload]
        coverage_80=_float(row, "coverage_80"),
        coverage_50=_float(row, "coverage_50"),
        boom_predicted=_float(row, "boom_predicted"),
        boom_observed=_float(row, "boom_observed"),
        bust_predicted=_float(row, "bust_predicted"),
        bust_observed=_float(row, "bust_observed"),
        season=None if rolled("season") else _int(row, "season"),
        week=None if rolled("week") else _int(row, "week"),
        position=None if rolled("position") else (str(row["position"]) if row.get("position") else None),
        band_low=None if rolled("band") or band is None else band,
        band_high=(
            None
            if rolled("band") or band is None or band >= repository.TRACK_RECORD_TOP_BAND
            else band + repository.TRACK_RECORD_BAND
        ),
    )


def summarise(rows: Sequence[Mapping[str, object]]) -> dict[str, list[Accuracy]]:
    """Sort grouping-set rows into their groups by their ``g_*`` flags.

    Pure, so the classification — the part that silently goes wrong if a flag
    is misread — is tested without a database.
    """
    groups: dict[str, list[Accuracy]] = {
        "overall": [],
        "position": [],
        "season": [],
        "season_position": [],
        "band": [],
        "weekly": [],
    }
    for row in rows:
        flags = (
            bool(row.get("g_season")),
            bool(row.get("g_week")),
            bool(row.get("g_position")),
            bool(row.get("g_band")),
        )
        key = {
            (True, True, True, True): "overall",
            (True, True, False, True): "position",
            (False, True, True, True): "season",
            (False, True, False, True): "season_position",
            (True, True, True, False): "band",
            (False, False, True, True): "weekly",
        }.get(flags)
        if key is not None:
            groups[key].append(accuracy_from_row(row))

    groups["position"].sort(key=lambda a: a.position or "")
    groups["season"].sort(key=lambda a: a.season or 0)
    groups["season_position"].sort(key=lambda a: (a.season or 0, a.position or ""))
    groups["band"].sort(key=lambda a: a.band_low or 0.0)
    groups["weekly"].sort(key=lambda a: (a.season or 0, a.week or 0))
    return groups


def outcome_from_row(row: Mapping[str, object]) -> Outcome:
    return Outcome(
        player_id=str(row["player_id"]),
        name=str(row.get("player_name") or row["player_id"]),
        headshot_url=(str(row["headshot"]) if row.get("headshot") else None),
        position=(str(row["position"]) if row.get("position") else None),
        team=(str(row["team"]) if row.get("team") else None),
        opponent=(str(row["opponent"]) if row.get("opponent") else None),
        is_home=(None if row.get("is_home") is None else bool(row["is_home"])),
        projected=float(row["projected"]),  # type: ignore[arg-type]
        floor=_float(row, "floor_points"),
        ceiling=_float(row, "ceiling_points"),
        actual=float(row["actual"]),  # type: ignore[arg-type]
    )


def build_scorecard(
    season: int,
    week: int,
    rows: Sequence[Mapping[str, object]],
    summary: Accuracy | None,
    *,
    size: int = SCORECARD_SIZE,
    min_projection: float = SCORECARD_MIN_PROJECTION,
) -> Scorecard:
    """The week's biggest beats and misses among players worth starting.

    Ordered by the size of the difference, ties broken by the higher
    projection and then the id, so the list is stable across requests.
    """
    outcomes = [outcome_from_row(row) for row in rows]
    eligible = [o for o in outcomes if o.projected >= min_projection]
    beats = sorted(
        (o for o in eligible if o.difference > 0),
        key=lambda o: (-o.difference, -o.projected, o.player_id),
    )[:size]
    misses = sorted(
        (o for o in eligible if o.difference < 0),
        key=lambda o: (o.difference, -o.projected, o.player_id),
    )[:size]
    return Scorecard(
        season=season,
        week=week,
        summary=summary,
        beats=tuple(beats),
        misses=tuple(misses),
        min_projection=min_projection,
    )


def scorecard_week(
    weekly: Sequence[Accuracy], season: int | None, week: int | None
) -> tuple[int, int] | None:
    """Which week the scorecard shows.

    The requested one when it has graded outcomes, otherwise the newest graded
    week in scope. Falling back rather than returning nothing is what makes the
    default request — a live week with no results yet — useful.
    """
    graded = [(a.season, a.week) for a in weekly if a.graded > 0 and a.season and a.week]
    if season is not None and week is not None and (season, week) in graded:
        return season, week
    scoped = [sw for sw in graded if season is None or sw[0] == season]
    return max(scoped) if scoped else None  # type: ignore[type-var]


async def get_track_record(
    session: AsyncSession,
    *,
    scoring_profile: str | None = None,
    season: int | None = None,
    week: int | None = None,
) -> TrackRecord:
    """Aggregate accuracy of stored projections, plus one week's scorecard.

    Args:
        session: Open async session.
        scoring_profile: League format. Actual points are scored in it, and so
            are the stored projections — the comparison is like for like.
        season: Restrict every aggregate to one season. ``None`` is all.
        week: The scorecard's week within ``season``. Falls back to the newest
            graded week in scope when it has no results.
    """
    profile = resolve_scoring_profile(scoring_profile)
    rows = await repository.fetch_track_record(session, scoring_profile=profile, season=season)
    groups = summarise(rows)

    chosen = scorecard_week(groups["weekly"], season, week)
    scorecard = None
    if chosen is not None:
        chosen_season, chosen_week = chosen
        outcomes = await repository.fetch_week_outcomes(
            session, season=chosen_season, week=chosen_week, scoring_profile=profile
        )
        summary = next(
            (a for a in groups["weekly"] if (a.season, a.week) == chosen), None
        )
        scorecard = build_scorecard(chosen_season, chosen_week, outcomes, summary)

    notices = [NOTICE_BACKFILL, NOTICE_DID_NOT_PLAY]
    if not rows:
        notices.append(
            "No stored projection has a recorded outcome yet, so there is nothing to grade."
        )
    if scorecard is not None and week is not None and (scorecard.season, scorecard.week) != (
        season, week
    ):
        notices.append(
            f"Week {week} has no recorded outcomes yet, so the scorecard shows "
            f"{scorecard.season} week {scorecard.week}, the latest graded week."
        )

    return TrackRecord(
        scoring_profile=profile,
        season=season,
        seasons=tuple(sorted({a.season for a in groups["season"] if a.season})),
        overall=groups["overall"][0] if groups["overall"] else None,
        by_position=tuple(groups["position"]),
        by_season=tuple(groups["season"]),
        by_season_position=tuple(groups["season_position"]),
        by_band=tuple(groups["band"]),
        weekly=tuple(groups["weekly"]),
        scorecard=scorecard,
        notices=tuple(notices),
    )

