"""Provider snapshots and the job run log.

Revision ID: 8bd687fede06
Revises: 0001_app_baseline
Created: 2026-08-07

Adds the three application-owned tables Layer 2 writes:

* ``weather_forecasts`` — forward-looking conditions per game. nflverse's
  ``temp``/``wind`` are observed after kickoff, so the upcoming season carries
  neither for any of its games.
* ``odds_snapshots`` — live market captures. nflverse ships only closing lines,
  posted for a small minority of future games.
* ``job_runs`` — execution log for every scheduled job, which is what makes
  failure recovery ("when did this last succeed?") answerable.

Both provider tables are append-only history rather than current state: line
movement and forecast revision are themselves predictive signals, and
overwriting would discard them. The unique index on
``(game_id, provider[, book], captured_at)`` is what makes re-running a job
idempotent instead of doubling the history; ``(game_id, captured_at DESC)``
serves the ``DISTINCT ON`` that resolves "latest known".

Generated by autogenerate, which is also the check that
``nflfp.db.alembic_guard`` works: it proposed these three tables and left all
eight ``raw_*`` warehouse tables alone.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8bd687fede06'
down_revision: str | None = '0001_app_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('records_written', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trigger', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'failed', 'skipped')", name=op.f('ck_job_runs_status_known')),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_job_runs_finished_after_started')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index('ix_job_runs_name_started', 'job_runs', ['job_name', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('book', sa.String(length=48), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spread_home', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('moneyline_home', sa.SmallInteger(), nullable=True),
    sa.Column('moneyline_away', sa.SmallInteger(), nullable=True),
    sa.Column('spread_home_open', sa.Float(), nullable=True),
    sa.Column('total_open', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('spread_home IS NULL OR spread_home BETWEEN -30 AND 30', name=op.f('ck_odds_snapshots_spread_plausible')),
    sa.CheckConstraint('total IS NULL OR total BETWEEN 20 AND 80', name=op.f('ck_odds_snapshots_total_plausible')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots'))
    )
    op.create_index('ix_odds_snapshots_latest', 'odds_snapshots', ['game_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index('uq_odds_snapshots_capture', 'odds_snapshots', ['game_id', 'provider', 'book', 'captured_at'], unique=True)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('wind_gust_mph', sa.Float(), nullable=True),
    sa.Column('precipitation_probability', sa.Float(), nullable=True),
    sa.Column('precipitation_in', sa.Float(), nullable=True),
    sa.Column('snowfall_in', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('roof_uncertain', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precipitation_probability IS NULL OR precipitation_probability BETWEEN 0 AND 100', name=op.f('ck_weather_forecasts_precip_probability_range')),
    sa.CheckConstraint('temperature_f IS NULL OR temperature_f BETWEEN -60 AND 130', name=op.f('ck_weather_forecasts_temperature_plausible')),
    sa.CheckConstraint('wind_mph IS NULL OR wind_mph BETWEEN 0 AND 120', name=op.f('ck_weather_forecasts_wind_plausible')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_forecasts'))
    )
    op.create_index('ix_weather_forecasts_latest', 'weather_forecasts', ['game_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index('uq_weather_forecasts_capture', 'weather_forecasts', ['game_id', 'provider', 'captured_at'], unique=True)


def downgrade() -> None:
    # CASCADE, deliberately.
    #
    # `feat_game_context` is an ETL-owned materialized view that reads these
    # two Alembic-owned tables — the one place a dependency crosses the
    # ownership boundary in that direction. Postgres therefore refuses a plain
    # DROP TABLE here.
    #
    # Cascading is the right resolution rather than a workaround: feature views
    # are derived, rebuildable artefacts with no state of their own, and the
    # weekly `pipeline full` publish already destroys them the same way when it
    # swaps the raw_* tables. `nflfp.jobs run build_features` restores them.
    op.execute("DROP TABLE IF EXISTS weather_forecasts CASCADE")
    op.execute("DROP TABLE IF EXISTS odds_snapshots CASCADE")
    op.drop_index('ix_job_runs_name_started', table_name='job_runs')
    op.drop_table('job_runs')
